- name: deploy web server using Ansible
  hosts: Dev,Prod
  become: yes
  vars: 
  - webserver: nginx
  - webserver_root_dir: /var/www/html
  tasks:
  - name: debug webserver variable value
    debug:
      msg: "the value of webserver variable is {{ webserver  }}"
  - name: web server is installed
    package:
      name: "{{ webserver }}"
      state: present
    register: nginx_install_output
  - name: web service is up and running
    service: 
      name: "{{ webserver }}"
      state: started
  - name: web server root directory exists
    file:
      path: "{{ webserver_root_dir }}"
      state: directory
  - name: static web site is deployed
    uri:
      url: https://raw.githubusercontent.com/abdennour/example-static-website/{{ git_branch }}/index.html
      dest: "{{ webserver_root_dir }}" #/ /usr/share/nginx/html
  - name: print in the terminal
    debug:
      var: nginx_install_output
  - name: copy the output
    copy:
      content: "{{ nginx_install_output }}"
      dest: /tmp/task1-output
