- name: play for display magic variables
  hosts: Prod,Dev
  tasks:
  - name: print inventory_hostname
    debug:
      var: inventory_hostname
  - name: print hostvars
    debug:
      var: hostvars
  - name: print group_names
    debug:
      var: group_names
  - name: print groups
    debug:
      var: groups
